export const UPDATE_LOCALES = 'locales/UPDATE_LOCALES';
export const SELECT_LOCALE = 'locales/SELECT_LOCALE';

export const PATIENT_LOGIN_FETCHING = 'PATIENT_LOGIN_FETCHING';
export const PATIENT_LOGIN_SUCCESS = 'PATIENT_LOGIN_SUCCESS';
export const PATIENT_LOGIN_ERROR = 'PATIENT_LOGIN_ERROR';