export const UPDATE_LOCALES = 'locales/UPDATE_LOCALES';
export const SELECT_LOCALE = 'locales/SELECT_LOCALE';

export const USER_LOGIN_SIGNUP_FETCHING = 'USER_LOGIN_SIGNUP_FETCHING';
export const USER_LOGIN_SIGNUP_SUCCESS = 'USER_LOGIN_SIGNUP_SUCCESS';
export const USER_LOGIN_SIGNUP_ERROR = 'USER_LOGIN_SIGNUP_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

/* PATIENT */
export const PATIENT_ASSESSMENT_QUESTIONS_FETCHING = 'PATIENT_ASSESSMENT_QUESTIONS_FETCHING';
export const PATIENT_ASSESSMENT_QUESTIONS_SUCCESS = 'PATIENT_ASSESSMENT_QUESTIONS_SUCCESS';
export const PATIENT_ASSESSMENT_QUESTIONS_ERROR = 'PATIENT_ASSESSMENT_QUESTIONS_ERROR';

export const PATIENT_ASSESSMENT_SUBMIT_FETCHING = 'PATIENT_ASSESSMENT_SUBMIT_FETCHING';
export const PATIENT_ASSESSMENT_SUBMIT_SUCCESS = 'PATIENT_ASSESSMENT_SUBMIT_SUCCESS';
export const PATIENT_ASSESSMENT_SUBMIT_ERROR = 'PATIENT_ASSESSMENT_SUBMIT_ERROR';

/* COUNSELOR */
export const COUNSELOR_PATIENT_LIST_FETCHING = 'COUNSELOR_PATIENT_LIST_FETCHING';
export const COUNSELOR_PATIENT_LIST_SUCCESS = 'COUNSELOR_PATIENT_LIST_SUCCESS';
export const COUNSELOR_PATIENT_LIST_ERROR = 'COUNSELOR_PATIENT_LIST_ERROR';

export const COUNSELOR_PATIENT_FETCHING = 'COUNSELOR_PATIENT_FETCHING';
export const COUNSELOR_PATIENT_SUCCESS = 'COUNSELOR_PATIENT_SUCCESS';
export const COUNSELOR_PATIENT_ERROR = 'COUNSELOR_PATIENT_ERROR';

/* DOCTOR */
export const DOCTOR_PATIENT_LIST_FETCHING = 'DOCTOR_PATIENT_LIST_FETCHING';
export const DOCTOR_PATIENT_LIST_SUCCESS = 'DOCTOR_PATIENT_LIST_SUCCESS';
export const DOCTOR_PATIENT_LIST_ERROR = 'DOCTOR_PATIENT_LIST_ERROR';

export const DOCTOR_PATIENT_FETCHING = 'DOCTOR_PATIENT_FETCHING';
export const DOCTOR_PATIENT_SUCCESS = 'DOCTOR_PATIENT_SUCCESS';
export const DOCTOR_PATIENT_ERROR = 'DOCTOR_PATIENT_ERROR';