export const UPDATE_LOCALES = 'locales/UPDATE_LOCALES';
export const SELECT_LOCALE = 'locales/SELECT_LOCALE';

// can be used to assign the initial state before making a request.
export const NULL_STATE = "NULL";

export const PATIENT_LOGIN_SIGNUP_FETCHING = 'PATIENT_LOGIN_SIGNUP_FETCHING';
export const PATIENT_LOGIN_SIGNUP_SUCCESS = 'PATIENT_LOGIN_SIGNUP_SUCCESS';
export const PATIENT_LOGIN_SIGNUP_ERROR = 'PATIENT_LOGIN_SIGNUP_ERROR';

export const PATIENT_ASSESSMENT_QUESTIONS_FETCHING = 'PATIENT_ASSESSMENT_QUESTIONS_FETCHING';
export const PATIENT_ASSESSMENT_QUESTIONS_SUCCESS = 'PATIENT_ASSESSMENT_QUESTIONS_SUCCESS';
export const PATIENT_ASSESSMENT_QUESTIONS_ERROR = 'PATIENT_ASSESSMENT_QUESTIONS_ERROR';

export const PATIENT_ASSESSMENT_SUBMIT_FETCHING = 'PATIENT_ASSESSMENT_SUBMIT_FETCHING';
export const PATIENT_ASSESSMENT_SUBMIT_SUCCESS = 'PATIENT_ASSESSMENT_SUBMIT_SUCCESS';
export const PATIENT_ASSESSMENT_SUBMIT_ERROR = 'PATIENT_ASSESSMENT_SUBMIT_ERROR';